sources:
  train_vegas_rgb8_img:
    description: PanSharpened, 8 bits RGBA Image from Spacenet Roads Train dataset for Vegas
    driver: rasterio
    parameters:
      data_spacenet_root:
        description: root directory for spacenet raster and vector folders for all AOIs
        type: str
        default: '/home/hayley/Data_Spacenet'
      img_id:
        description: img id
        type: int
    args:
      urlpath: '{{ data_spacenet_root }}/AOI_2_Vegas_Roads_Train/RGB-PanSharpen-8bits/RGB-PanSharpen-8bits_AOI_2_Vegas_img{{ img_id }}.tif'
      chunks:
        band: 1
        x: 256
        y: 256
        
  train_rgb8_img:
    description: PanSharpened, 8 bits RGBA Image from Spacenet Roads Train dataset
    driver: rasterio
    parameters:
      data_spacenet_root:
        description: root directory for spacenet raster and vector folders for all AOIs
        type: str
        default: '/home/hayley/Data_Spacenet'
      aoi:
        description: AOI description for a particular city. Must be one of AOI_2_Vegas, AOI_3_Paris, AOI_4_Shanghai, AOI_5_Khartoum
        type: str
        allowed: ["AOI_2_Vegas", "AOI_3_Paris", "AOI_4_Shanghai", "AOI_5_Khartoum"]     
      img_id:
        description: img id
        type: int
    args:
      urlpath: '{{ data_spacenet_root }}/{{ aoi }}_Roads_Train/RGB-PanSharpen-8bits/RGB-PanSharpen-8bits_{{ aoi }}_img{{ img_id }}.tif'
      chunks:
        band: 1
        x: 256
        y: 256
        
  train_mask_img:
    description: Mask raster files (dtype=uint8) generated by rasterinzing the road buffer vectors
    driver: rasterio
    parameters:
      data_spacenet_root:
        description: root directory for spacenet raster and vector folders for all AOIs
        type: str
        default: '/home/hayley/Data_Spacenet'
      aoi:
        description: AOI description for a particular city. Must be one of AOI_2_Vegas, AOI_3_Paris, AOI_4_Shanghai, AOI_5_Khartoum
        type: str
        allowed: ["AOI_2_Vegas", "AOI_3_Paris", "AOI_4_Shanghai", "AOI_5_Khartoum"]     
      img_id:
        description: img id
        type: int
    args:
      urlpath: '{{ data_spacenet_root }}/{{ aoi }}_Roads_Train/Mask/mask_{{ aoi }}_img{{ img_id }}.tif'
      chunks:
        band: 1
        x: 256
        y: 256
          
  train_vec:
    description: Vector files describing road annotations for the corresponding RGB images
    driver: geojson
    parameters:
      data_spacenet_root:
        description: root directory for spacenet raster and vector folders for all AOIs
        type: str
        default: '/home/hayley/Data_Spacenet'
      aoi:
        description: AOI description for a particular city. Must be one of AOI_2_Vegas, AOI_3_Paris, AOI_4_Shanghai, AOI_5_Khartoum
        type: str
        allowed: ["AOI_2_Vegas", "AOI_3_Paris", "AOI_4_Shanghai", "AOI_5_Khartoum"] 
      vec_type:
        description: vector type, either "spacenetroads" for the centerlines or "buffer" for buffer polygons
        type: str
        allowed: ["spacenetroads", "buffer"]
      img_id:
        description: img id
        type: int
    args:
      urlpath: '{{ data_spacenet_root }}/{{ aoi }}_Roads_Train/geojson/{{ vec_type }}/{{ vec_type }}_{{ aoi }}_img{{ img_id }}.geojson'
      chunks:
        band: 1
        x: 256
        y: 256


  train_rbuffer_vec:
    description: Vector files describing road buffer polygon-type shapes for the corresponding RGB images
    driver: geojson
    parameters:
      data_spacenet_root:
        description: root directory for spacenet raster and vector folders for all AOIs
        type: str
        default: '/home/hayley/Data_Spacenet'
      aoi:
        description: AOI description for a particular city. Must be one of AOI_2_Vegas, AOI_3_Paris, AOI_4_Shanghai, AOI_5_Khartoum
        type: str
        allowed: ["AOI_2_Vegas", "AOI_3_Paris", "AOI_4_Shanghai", "AOI_5_Khartoum"] 
      img_id:
        description: img id
        type: int
    args:
      urlpath: '{{ data_spacenet_root }}/{{ aoi }}_Roads_Train/geojson/buffer/buffer_{{ aoi }}_img{{ img_id }}.geojson'
#       chunks:
#         band: 1
#         x: 256
#         y: 256
      
  train_rline_vec:
    description: Vector files describing road centerline for corresponding RGB images
    driver: geojson
    parameters:
      data_spacenet_root:
        description: root directory for spacenet raster and vector folders for all AOIs
        type: str
        default: '/home/hayley/Data_Spacenet'
      aoi:
        description: AOI description for a particular city. Must be one of AOI_2_Vegas, AOI_3_Paris, AOI_4_Shanghai, AOI_5_Khartoum
        type: str
        allowed: ["AOI_2_Vegas", "AOI_3_Paris", "AOI_4_Shanghai", "AOI_5_Khartoum"] 
      img_id:
        description: img id
        type: int
    args:
      urlpath: '{{ data_spacenet_root }}/{{ aoi }}_Roads_Train/geojson/spacenetroads/spacenetroads_{{ aoi }}_img{{ img_id }}.geojson'
#       chunks:
#         band: 1
#         x: 256
#         y: 256

  train_ids:
    description: json file containing image ids for each city(vegas, paris, shanghai, khartoum) and each datatype(rgb8, mask. rbuffer, rline)
    driver: geojson
    parameters:
      data_spacenet_root:
        description: root directory for spacenet raster and vector folders for all AOIs
        type: str
        default: '/home/hayley/Data_Spacenet'
    args:
      urlpath: '{{ data_spacenet_root }}/train_ids.json'
      
    

  